### ISSUE TITLE
Add support to merge logs with time ordering

### ISSUE THREAD

**Issue by zysimplelife** [pamburus/hl#28]
Hi 

It would be very useful if hl can merge logs based on time.
Those logs might comes from different component in a big system.  In order to trace issues,  having a time ordered a logs is very useful.  Hopefully it can be supported in this tool

best regard

**Comment by pamburus** [comment]
Hi

Thanks for your interest.

Yes, it will be very useful, and it is one of the most wanted features by me personally.
But at the same time it is the most complicated especially taking into account that the sources can be very different, including stream-only pipes (without random access), gzip files, etc., as well as the amount of data from these sources may be up to tenths or hundreds of gigabytes. So, reading all these data into memory for sorting is not an acceptable solution.

I have some progress on this feature - I've already implemented indexing of such data with relatively small indexes and supported regular log files, and stdin (by storing compressed chunks of copied data in memory). But there is no support for other pipes (besides stdin), i.e. bash process substitution and gzipped files (since they do not provide random access). Also, there is no support sorting while streaming (-P | --paging=never), it could be very helpful for streaming kubernetes logs from multiple containers.

**Comment by pamburus** [comment]
Hi @zysimplelife 

Sorting by timestamp has been implemented and is available in [v0.20.0-beta.3](https://github.com/pamburus/hl/releases/tag/v0.20.0-beta.3).
There are some limitations though, for example, sorting is not supported with gzip files and with live streaming (follow mode).

Nevertheless, I hope it will be useful to you.

**Comment by pamburus** [comment]
Also, support for sorting messages on the fly in follow mode has been added starting from `v0.20.0-beta.12`.
To enable this mode `-F` or `--follow` option should be used with a list of pipes to be followed.
Bash `<(command)` syntax can be used, for example `<(tail -f app1.log) <(tail -f app2.log)` .
Currently only pipes are supported, so to follow a file that is being written, `tail -f` command should be used.
Support for `tail -f` follow mode out of the box likely will be added later.
