### ISSUE TITLE
Level `INF` (uppercase) not parsed correctly

### ISSUE THREAD

**Issue by lauclld** [pamburus/hl#288]
Hello,

First, thanks for the great work!

While trying to tweak the config file, I realized that the `info` level does not parse `INF` correctly. Lowercase `inf` works fine. You can try with the attached files.

I'm on Windows with v0.29.5.

Thanks,
Laurent
[example.log](https://github.com/user-attachments/files/15566806/example.log)
[example-hl-config.yaml.txt](https://github.com/user-attachments/files/15566813/example-hl-config.yaml.txt)

**Comment by lauclld** [comment]
Same with v0.29.6. Thanks.

**Comment by pamburus** [comment]
Created issue [#568](https://github.com/mehcode/config-rs/issues/568) for the [config-rs](https://github.com/mehcode/config-rs) crate.
This problem seems to be specific to the YAML format, because in most other formats, strings must be enclosed in quotes.

I am thinking about ignoring case for levels. This would not only work around the problem, but also make it easier to configure for different spellings.

**Comment by lauclld** [comment]
Thanks for the quick fix and the workaround. 👍
