### ISSUE TITLE
ASCII Colors in Message Supported?

### ISSUE THREAD

**Issue by wes8ty** [pamburus/hl#404]
Is ASCII color decoding supported in `hl` if it is in the message? I know this worked for me at some point.

Command
```
hl --color always filename.log --since -1d
```

Output in Terminal
```
Aug 19 04:04:07.798 PM EDT |INF| "[\u001b[1mINFO \u001b[0m] [\u001b[34mMainThread\u001b[0m] [\u001b[36m__init__.py         \u001b[0m:\u001b[36m1706\u001b[0m] \u001b[1mFinished processing state st_aws_job_standby exit callbacks.\u001b[0m"
```

**Comment by pamburus** [comment]
Unfortunately, it never had proper support for colors in either messages or field values.
But to improve readability of messages and field values with newline and tab characters, they were printed as-is, without any processing. 

One of the side effects of such a simple approach was some sort of "support" for ANSI colors.
But this "support" came with a lot of problems, including ambiguous output of messages/fields containing spaces, quotes, and other special characters. Sometimes it was impossible to parse them (even visually by a human) and understand where a field or message starts and ends, and what the exact value is.

Also, passing arbitrary control characters could have dangerous effects, because they could contain terminal control sequences other than just changing colors, and thus corrupt the output.

So now both fields and messages are printed unambiguously, enclosed in the most appropriate quotes as needed, and with proper escaping for special characters that might corrupt the output or cause confusion.

There is some unfinished work to improve formatting of long messages and fields, as well as values containing some newline and tab formatting, but this does not yet address support for ANSI colors in values.

It seems that ideally to support ANSI colors in values, the ANSI escape sequences should be parsed and only safe sequences should be processed, all others should be ignored and discarded. And it should probably be turned on/off by a separate option, since it is not obvious which variant of output is desired.

I will think about adding support for ANSI colors in values when I have some time.

But in the meantime, I would recommend that you investigate whether it is possible to handle this problem from the other side. It looks like you already have some logs that are supposed to be structured, at least they have a log level and some special formatting that could itself be replaced with JSON or logfmt format. This wrapping of unstructured and colored logs into a message field of structured logs seems unnatural. Presumably the log level information is lost at this point, as well as the benefits of structured logging, which allows you to filter/search/query by key/value pairs.

If it is not possible to change the format of the logs in your case, could you please describe why and what is the usage scenario and logging configuration which that leads to this wrapping?

If anyone else needs this feature, please let me know as well. The more usage scenarios that require this feature, the more likely it will be implemented soon.

**Comment by wes8ty** [comment]
Thanks for the information! I will try to remove those coloring stuff using regex.
